### ISSUE TITLE
Couldn't Generate Key

### ISSUE THREAD

**Issue by bellyfat** [bitsquare/bitsquare#611]
Windows 8
RAM 8GB
Bitsquare 0.4.9.6

Error on Start: Couldn't Generate Key
So no way to trade and cannot do anything but add banking information.

**Comment by ManfredKarrer** [comment]
Did u run from source or from the jar file instead the exe? If so you need to follow exactly the steps in the build.md file.

**Comment by bellyfat** [comment]
Ran from .exe

**Comment by bellyfat** [comment]
This has followed me the last two releases, I thought it would come clear so waited and used another computer, it has not.

**Comment by bellyfat** [comment]
I will delete all the appdata file and reinstall. Maybe thats the best path if nobody else is experiencing this error

**Comment by ManfredKarrer** [comment]
I had not heard of others, so seems to be soem local OS issue... If u run the exe the packed jdk should be used which has the right setup. Prob. u have installed a local jdk as well and for some reason that is used. Can u try to deactivate that local jdk (remove temporary JAVA_HOME variable,...)?
Maybe the path to your bitsquare app has some chars which cause issues?

**Comment by bellyfat** [comment]
uninstalling, deleting appdata bitsquare and reinstalling was the only thing that worked.

**Comment by ManfredKarrer** [comment]
Yes I saw a few times strange things with the windows installation. Seems the application directory where the app itself is not the user data is not cleaning up correctly at installations and so old jdk or whatever remains there.
The Java installer is not very reliable with all OS, maybe we change to another installer in the future.
